numbers=(10,20,30,40,50)
numbers=list(numbers)
numbers.append(60)
numbers[2]=35
numbers=tuple(numbers)
print(numbers)

values=(15,5,30,25,10)
values=list(values)
values.sort()
values=tuple(values)
print(values)

fruits=('apple','banana','cherry','banana','mango','banana')
fruits=list(fruits)
fruits.count('banana')

fruits.remove('banana')
fruits.remove('banana')
fruits.remove('banana')
fruits=tuple(fruits)
print(fruits)

names=('Alice','Bob','Charlie','David')
names=list(names)
names.sort(reverse=True)
names=tuple(names)
print(names)

colors=('red','blue','green')
colors=list(colors)
colors.insert(1,'yellow')
colors.append('purple')
colors.append('orange')
colors=tuple(colors)
print(colors)